language: python
python:
  - "3.4"
before_install:
  - wget http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz
  - tar zxvf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'
  - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
