language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - wget http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.13.3.tar.gz
  - tar zxvf sip-4.13.3.tar.gz
  - cd sip-4.13.3/
  - python configure.py
  - make
  - sudo make install
  - cd ..
  - python -c 'import sip'
  - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
